# Generated by Django 4.1.2 on 2022-11-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0038_alter_season_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
